### ISSUE TITLE
wondor : ToDo

### ISSUE THREAD

**Issue by kimhanui** [kimhanui/Login-SG#8]
## 기본
- [ ] csrf, cors 에러 해결하기
- [x] `validation` 예외 처리하기

## 이슈 todo
- [ ] 매 요청(access token으로도)시 `getAuthentication` 하면서 DB에 사용자 정보를 요청한다.
   > access token vs refresh token의 중요한 차이점(at는 서명만 맞으면되고, rt는 서명+db에서 일치하는 사용자인지까지 확인)
- [ ] mailing 비동기로 처리 -> **axios의 async, await로 처리하려했는데 잘 안된 것 같다..**

## JWT 없이 접근
- [x] 회원가입 기능 구현 (`/user/register`)
  - [x] 회원가입/로그인 페이지 (아무 권한 없을 경우만)
  > 비밀번호 : 4~12자리, 알파벳(대소문자), 숫자, 특수기호(`!, @, #, $, %, ^, &, *`)만 허용

- [x] 로그인 기능 구현 (`/user/login`)
  - [x] 3번 시도할 수 있음. 
  - [x] JWT 발급
      - [x] access token (유효시간: 30분)
      - [x] refresh token (유효시간: 2주) -> db에 저장

  > 로그아웃 기능 구현
  >   - [x] 로그아웃 버튼 누르면 client 저장소에서 `access token` 삭제, server에서도 db에서 `refresh token`삭제

- [x] ~**[jwt]** 비밀번호 찾기 (`/user/findme`)~-> **jwt 없이 비밀번호 초기화로 변경 (`/user/mailpw`)**
  - [ ] ~비밀번호 찾는 페이지 react (아무 권한 없을 경우만)~
  - [x] 기능: 
      - [ ] ~우선, 3번 시도할 수 있음. (횟수는 비번 업데이트할 때마다 초기화)~
      - [x] 다음은 메일 전송으로 비번 바꾼다.

- [x] `accesstoken` 재발급 (`/user/reissueactoken`)

## 반드시 JWT 필요한 접근
**기본**
- [x] 모든 요청에 jwt 검증하는 필터 끼워넣기

- [x] ~**[jwt]** 로그인 이후 요청( `/sandbox` + `header에 토큰추가`)~ -> **홈에서 사용자 email, `role`표시로 권한에 따라 다른 페이지 이동가능한지 보는 것으로 변경함**
  - [ ] ~sandbox 페이지 react (권한 있을 경우만)~

- [x] **[jwt]** admin 유저 관리 (`/admin/userlist`, `/admin/updateuser`)
  - [x] admin은 유저의 모든 정보를 read/~update~해줄 수 있다. -> **update는 server API는 있지만, js문법때문인지.. 화면 구성에 문제가 생겨 포기**
    - [x] 단 비밀번호는 못본다. (salt로 단방향 해싱돼있어서 decrypt 불가능. 대신 업데이트 해 줄 순 있음)

## 특징
- 예외 핸들링 `dispatcherServlet` in/out 하여 예외 응답 포맷 통일
- `.gitignore`로 `secret key` 등 숨김
- 클린 코드..? -> **server만(front는 코드가 너무 지저분함)**
- DB설계시 컬럼별 길이, 타입 지정함
- 예외 메시지가 `한글` or `영어`로 나옴.. 
- 비밀번호는 관리자도 볼 수 없다. 단방향 해싱이기때문
- frontend 토큰 저장: localStorage
- refresh token 처리
  - refresh token을 갱신하는 api를 만들고, front에서 요청 보낸 후 `REQUEST_TIMEOUT` 상태코드를 받으면 바로 refresh token으로 access token을 발급받아 localStorage에 저장한다. but, 실패한 요청을 재시도하는건 사용자에게 수동으로 재시도하라는 알림을 띄워줌.
